# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fourier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(default='null', upload_to='uploads/'),
        ),
    ]
