# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-24 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fourier', '0002_post_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(default='null', max_length=200, upload_to='uploads/'),
        ),
    ]
